### PR TITLE
Changes for optable YOP

### LINKED ISSUE #568: Correct OPTABLE(YOP,LIST) output to match HLASM
The list of supported mnemonics when running with OPTABLE(YOP) is incorrect. It should match HLASM's output for the option.

### PR DESCRIPTION
**Pull request by abekornelis**
Resolves #568 Correct OPTABLE(YOP,LIST) output to match HLASM

### CODE REVIEW

File: src/az390.java [hunk 1]
```diff
@@ -2410,6 +2421,41 @@ else if (tz390.op_trace_type[index]==613)                          // #533
...
+ * The mnemonic portion occupies the first 8 positions of the ReportEntry
+ * and contains only uppercase characters and digits.
+ * Digits should sort higher than alphabetic characters.
+ */
+public class ReportEntryComparator implements Comparator<String>                   // #568
+ {@Override                                                                        // #568
+  public int compare(String str1, String str2)                                     // #568
+   {// special case: entries consisting of a single space sort first!              // #568
+    if (str1.charAt(0) == ' ') return 1;  // blank entry always smaller            // #568
+    if (str2.charAt(0) == ' ') return -1; // blank entry always smaller            // #568
```
Comment (jyganci) [inline src/az390.java:2435]: What if both strings are blank?

File: src/az390.java [hunk 2]
```diff
@@ -2410,6 +2421,41 @@ else if (tz390.op_trace_type[index]==613)                          // #533
...
+    for (int i=0; i<7; i++)                                                        // #568
```
Comment (jyganci) [inline src/az390.java:2436]: I assume that you know both strings have length at least 7.

File: src/az390.java [hunk 3]
```diff
@@ -2410,6 +2421,41 @@ else if (tz390.op_trace_type[index]==613)                          // #533
...
+     {char c1 = str1.charAt(i);                                                    // #568
+      char c2 = str2.charAt(i);                                                    // #568
+      if (c1 == c2) {} // continue on to next char                                 // #568
+      else // we found different characters                                        // #568
```
Comment (jyganci) [inline src/az390.java]: Replace with "if (c1 != c2)" ???

File: src/az390.java [hunk 4]
```diff
@@ -2410,6 +2421,41 @@ else if (tz390.op_trace_type[index]==613)                          // #533
...
+       {if (c1 == ' ') return -1; // Mnemonic 2 is longer                          // #568
+        if (c2 == ' ') return 1;  // Mnemonic 1 is longer                          // #568
```
Comment (jyganci) [inline src/az390.java:2442]: Can they be the same length?

File: src/az390.java [hunk 5]
```diff
@@ -2410,6 +2421,41 @@ else if (tz390.op_trace_type[index]==613)                          // #533
...
+         {if (c2 <= '9') return (c1-c2); // compare two digits                     // #568
+          else return 1;                 // digit always larger                    // #568
+          }                                                                        // #568
+        else // c1 is not numeric                                                  // #568
+         {if (c2 <= '9') return -1; // digit always larger                         // #568
+          else return (c1-c2);      // compare two alphabetic chars                // #568
+          }                                                                        // #568
+        }                                                                          // #568
+      }                                                                            // #568
+    return 0; // First 8 characters are equal                                      // #568
```
Comment (jyganci) [inline src/az390.java:2453]: The loop only looked at 7 characters??? (indicies 0-6).

File: src/az390.java (hunk 1 above)
Comment (abekornelis) [reply src/az390.java:2435]: Then they are the same and the sequence does not matter.

File: src/az390.java (hunk 3 above)
Comment (abekornelis) [reply src/az390.java]: I did that to allow for the comments. I have put comments on a separate line, and followed your suggestion. 
Looks better this way, indeed. Thanks.

File: src/az390.java (hunk 4 above)
Comment (abekornelis) [reply src/az390.java:2442]: No, that would mean we have identical mnemonics. Should never occur. If it does we'll have bigger problems than this piece of compare/sort logic.

File: src/az390.java (hunk 5 above)
Comment (abekornelis) [reply src/az390.java:2453]: I updated the stop criterion. Apparently - for available test cases - it was good enough. But you are correct: it should have inspect all 8 characters of the mnemonic.

File: src/az390.java (hunk 1 above)
Comment (jyganci) [reply src/az390.java:2435]: If line 2434 is trun, code returns 1, not checking whether str2.charAt(0) is blank. Seems to me that code should return 0 in this case.

Comment (abekornelis) [reply src/az390.java:2435]: As the comments indicate, a blank entry is by definition smaller. Even if they both are blank, equality does not matter, we simply declare the first blank we encounter the smaller of the two. Since the entries are discarded after sorting, the order of the blank entries is irrelevant, as long as they do sort up front.
I could add code to detect equality of entries staged for suppression, but that's more code and - to my mind - more confusing. If you still are opined differently, I'll make the change, though. As stated - it's irrelevant. What's more readable is a matter of style and taste :-)

**Review by jyganci — APPROVED** [review]
