### PR TITLE
Fix X2C and Index issue - No whitespace changes

### LINKED ISSUE #214: Macro functions X2B and X2C to return multi-byte values
Currently the X2B and X2C functions return only single-byte values. We need to extend the return values of these functions to accommodate multi-byte values.

### LINKED ISSUE #216: RPI 1646: X2C/X2B errors with multi-byte input data
Raised by Fred van der Windt 2021/02/03
X2C and X2B functions fail on multi-byte input data. See mail by Fred van der Windt dd 2021-03-02 12:18

### LINKED ISSUE #438: X2C issue
X2C function only works correctly for one byte hexadecimal string length input. X2C and X2B functions fail on multi-byte input data.

Example:

`&SRC     SETC  X2C('30313233343536373839616263646566414243444546')`

Returns an error, during macro expansion process:

```
14:44:20 FQM8921C  MZ390 START USING z390 V1.7.07 ON J2SE 1.8.0_333 05/12/22
MZ390E abort 84 file=1 line=43 internal system exception - java.lang.NumberFormatException: For input string: "30313233343536373839616263646566414243444546"
AZ390E error 165       (1/43)42   * MZ390E abort 84 file=1 line=43 internal system exception - java.lang.NumberFormatException: For input string: "30313233343536373839616263646566414243444546"
14:44:24 FQM8921C  MZ390 ENDED   RC=16 SEC= 3 MEM(MB)= 74 IO=181
```

**Proposed fix**
This can be fixed in function exec_pc_x2c in mz390.java.

**Original**

```
 private void exec_pc_x2c(){
    	/*
    	 * convert hex string to char string
    	 */
    	check_setc_quotes(1); // RPI 1139
    	setc_value1 = get_setc_stack_value();
    	seta_value = Integer.valueOf(setc_value1,16);
		setc_value = ""
	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 24]
	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 16 & 0xff]         
	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 8  & 0xff]
	       + (char)tz390.ebcdic_to_ascii[seta_value        & 0xff]		       ;
	put_setc_stack_var();
    }
```

**Fixed**

```
    private void exec_pc_x2c(){
    	/*
    	 * convert hex string to char string
    	 */
    	check_setc_quotes(1); // RPI 1139
    	setc_value1 = get_setc_stack_value();
//ING    	seta_value = Integer.valueOf(setc_value1,16);
//ING	setc_value = ""
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 24]
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 16 & 0xff]         
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value >>> 8  & 0xff]
//ING	       + (char)tz390.ebcdic_to_ascii[seta_value        & 0xff]	 
//ING	       ;
        StringBuilder stb = new StringBuilder("");
        for (int i = 0; i < setc_value1.length(); i += 2) {
            String str = setc_value1.substring(i, i + 2);
            stb.append((char) Integer.parseInt(str, 16));
        }
        setc_value = stb.toString(); 	
        put_setc_stack_var();
    }

```

### LINKED ISSUE #439: INDEX  issue
The INDEX function is not properly parsed when it is used in an expression.

Example:

```
&D       SETA     (((INDEX('!NO !YES','!&DCR')+3)/4)-1)
         AIF      (&D EQ 0 OR &D EQ 1).DCROK
         MNOTE    8,'FQ35 Characters decorate option "&DCR" invalid.'
         MEXIT
.DCROK   ANOP

```

Returns an error:

` *MZ390E error  38        (14/45)45 expression parsing error - prev op =IX next op =+
` 

**Proposed fix**

This can be fixed in exp_action array in mz390.java.

**Original**

 	int[] exp_action = {  
			1, 3, 3, 1, 0, 1, 1, 8, 1, 3, 1, 1, 1, 1, 3, // 1 +-  prev add/sub
			2, 2, 3, 2, 0, 2, 2, 8, 2, 3, 2, 2, 2, 2, 3, // 2 * / prev mpy/div  RPI 214
			3, 3, 3, 4, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 3 (   prev open (...) RPI 274, RPI 647
			3, 3, 3,11, 3, 3, 3, 8,11, 3, 3, 3, 3, 3, 3, // 4 )   prev var subscript RPI 559
			0, 0, 3, 5, 5, 5, 5, 8, 0, 3, 0, 0, 0, 0, 3, // 5 .   prev concat
			3, 3, 3, 6, 3, 6, 3, 8, 3, 3, 3, 3, 3, 3, 3, // 6 ~   prev terminator
			3, 3, 3, 7, 3, 7, 7, 8, 0, 3, 7, 7, 7, 7, 3, // 7 LL  logical compares //RPI144 (was 1,2 now 3,3)
			3, 3, 3, 0, 0, 0, 0, 8, 0, 3, 0, 0, 0, 0, 3, // 8 '   string '....'
			3, 3, 3,10, 0, 0, 0, 0, 9, 3, 0, 0, 0, 0, 3, // 9 ,   substring '...'(e1,e2)
			12,12, 3,12,12,12,12, 3,12,03,12,12,12,12, 3, //10 ?'  prefix operator  //RPI145, RPI196, RPI 353 rpi 938 O3 FOR DOUBLE ?' etc
			3, 3, 3,13, 3, 0, 3, 3, 0, 3,13,13,13,13, 3, //11 NOT logical
			3, 3, 3,14, 3, 0, 3, 3, 0, 3, 3,14,14,14, 3, //11 AND logical
			3, 3, 3,15, 3, 0, 3, 3, 0, 3, 3, 3,15,15, 3, //11 OR  logical
			3, 3, 3,16, 3, 0, 3, 3, 0, 3, 3, 3, 3,16, 3, //11 XOR logical
			0, 0, 0,17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3 //10 ?'  prefix operator 

**Fixed**

```
	int[] exp_action = {  
			1, 3, 3, 1, 0, 1, 1, 8, 1, 3, 1, 1, 1, 1, 3, // 1 +-  prev add/sub
			2, 2, 3, 2, 0, 2, 2, 8, 2, 3, 2, 2, 2, 2, 3, // 2 * / prev mpy/div  RPI 214
			3, 3, 3, 4, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 3 (   prev open (...) RPI 274, RPI 647
			3, 3, 3,11, 3, 3, 3, 8,11, 3, 3, 3, 3, 3, 3, // 4 )   prev var subscript RPI 559
//ING	                0, 0, 3, 5, 5, 5, 5, 8, 0, 3, 0, 0, 0, 0, 3, // 5 .   prev concat
                        5, 5, 3, 5, 5, 5, 5, 8, 0, 3, 0, 0, 0, 0, 3, // 5 .   prev concat			
			3, 3, 3, 6, 3, 6, 3, 8, 3, 3, 3, 3, 3, 3, 3, // 6 ~   prev terminator
			3, 3, 3, 7, 3, 7, 7, 8, 0, 3, 7, 7, 7, 7, 3, // 7 LL  logical compares //RPI144 (was 1,2 now 3,3)
			3, 3, 3, 0, 0, 0, 0, 8, 0, 3, 0, 0, 0, 0, 3, // 8 '   string '....'
			3, 3, 3,10, 0, 0, 0, 0, 9, 3, 0, 0, 0, 0, 3, // 9 ,   substring '...'(e1,e2)
			12,12, 3,12,12,12,12, 3,12,03,12,12,12,12, 3, //10 ?'  prefix operator  //RPI145, RPI196, RPI 353 rpi 938 O3 FOR DOUBLE ?' etc
			3, 3, 3,13, 3, 0, 3, 3, 0, 3,13,13,13,13, 3, //11 NOT logical
			3, 3, 3,14, 3, 0, 3, 3, 0, 3, 3,14,14,14, 3, //11 AND logical
			3, 3, 3,15, 3, 0, 3, 3, 0, 3, 3, 3,15,15, 3, //11 OR  logical
			3, 3, 3,16, 3, 0, 3, 3, 0, 3, 3, 3, 3,16, 3, //11 XOR logical
			0, 0, 0,17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3 //10 ?'  prefix operator 
	}; 
```

### PR DESCRIPTION
**Pull request by adelosa**
Submitted on behalf of @FredvanderWindt. 
Applies changes previously submitted by Fred without updating any whitespaces which is causing some issues for review.
* Fixes #438 x2c issue 
* Fixes #439 index issue
* Fixes #214
* Fixes #216 
@FredvanderWindt - please check I have captured all the relevant non-whitespace updates.

### CODE REVIEW

**Review by dsh33782 — DISMISSED** [review]
Looks good to me.

File: src/mz390.java [hunk 1]
```diff
@@ -993,7 +995,7 @@ public  class  mz390 {
 			2, 2, 3, 2, 0, 2, 2, 8, 2, 3, 2, 2, 2, 2, 3, // 2 * / prev mpy/div  RPI 214
 			3, 3, 3, 4, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 3 (   prev open (...) RPI 274, RPI 647
 			3, 3, 3,11, 3, 3, 3, 8,11, 3, 3, 3, 3, 3, 3, // 4 )   prev var subscript RPI 559
-			0, 0, 3, 5, 5, 5, 5, 8, 0, 3, 0, 0, 0, 0, 3, // 5 .   prev concat
+			5, 5, 3, 5, 5, 5, 5, 8, 0, 3, 0, 0, 0, 0, 3, // 5 .   prev concat
```
Comment (jyganci) [inline src/mz390.java:998]: I would like to see a test program that I can assemble that has the problem without the fix and is okay with the fix.

File: src/mz390.java [hunk 2]
```diff
@@ -12315,21 +12317,20 @@ private void exec_pc_x2b(){
...
+	private void exec_pc_x2c(){
+		/*
+		 * convert hex string to char string
+		 */
+		check_setc_quotes(1); // RPI 1139
+		setc_value1 = get_setc_stack_value();
+		StringBuilder stb = new StringBuilder("");
+		for (int i = 0; i < setc_value1.length(); i += 2) {
+			String str = setc_value1.substring(i, i + 2);
+			stb.append((char) Integer.parseInt(str, 16));
```
Comment (jyganci) [inline src/mz390.java]: The above line adds an ASCII character to stb. Should be an EBCDIC character. The line should be
```
stb.append((char) tz390.ebcdic_to_ascii[Integer.parseInt(str, 16)]);
```
Attached file contains output from test program that was assembled with mz390.java modified as suggested. 
[TX2C.TXT](https://github.com/z390development/z390/files/9639451/TX2C.TXT)

**Comment by jyganci** [comment]
See the comments in "Files changed". The X2C change has an error. For me, I need a complete source module that illustrates the INDEX problem before and after the fix.

**Comment by FredvanderWindt** [comment]
See https://github.com/z390development/z390/issues/439

**Comment by jyganci** [comment]
I saw the code snippet in the INDEX issue. I am asking for an example of
something I can assemble. While I can probably concoct one based on the
code snippet on my own, I'd rather see what you used.

File: src/mz390.java (hunk 1 above)
Comment (jyganci) [reply src/mz390.java:998]: I created a short test program (see attached files) that has a test macro that uses the code snippet provided for the INDEX issue. The above new line fixed the problem.

Unrelated to the current pull request, the test program uncovered another issue. If you look at the test output, the first of the 3 tests yields the "invalid" MNOTE, as expected. However, the value for the &D SETA variable is -1, as expected, but is displayed as 1 (see the added MNOTEs in the output). I will open a new issue for this.

[TINDEX.MLC.TXT](https://github.com/z390development/z390/files/9641149/TINDEX.MLC.TXT)
[TINDEX.PRN.TXT](https://github.com/z390development/z390/files/9641150/TINDEX.PRN.TXT)

Comment (jyganci) [reply src/mz390.java:998]: I just tried the negative test on my TK4 (MVS) system. It also displayed the negative value as a positive value. Since this system uses ASMF, it would be nice to see what HLASM displays. Right now I will hold off opening a new issue.

**Comment by jyganci** [comment]
I updated the comments in "Files changed", saying I'd created my own test program for the INDEX-related change. Assembling that test program indicates that that change (mz390.java new line 998) does seem to fix the INDEX issue.

With regards to the X2C issue, there has been no response to the problem I pointed out for mz390.java new line 12329.

**Comment by adelosa** [comment]
@FredvanderWindt -- Are you able to respond to @jyganci queries above.

**Comment by FredvanderWindt** [comment]
I am not sure how to respond to @jyganci queries regarding the X2C issue. We use this fix to process X2C with long hex strings and the values are assembled correctly. I included an example in the issue I created.

**Comment by FredvanderWindt** [comment]
That was issue #438 (now closed).

**Comment by jyganci** [comment]
1. The fix for INDEX, mz390.java line 998, is fine.
2. The fix for X2C produces ASCII character output. It should be EBCDIC character output.
3. The original exec_pc_x2c() code converted its value from ASCII to EBCDIC.
4. The one line suggested change to the fix simply does the same thing.

Attached is a screenshot from the HLASM Language Reference manual that documents X2C:

HLASM-X2C



Note that X2C('F3') has the value '3', which in hexadecimal is F3 in EBCDIC.

Sample test program follows.
```
TX2C     CSECT
         GBLC &SRC
*
*        Test X2C with EBCDIC '2' - hex byte F2
&SRC     SETC X2C('F2')
         DC    C'&SRC'
*
*        Test X2C with EBCDIC 'A2' - hex bytes C1F2
&SRC     SETC X2C('C1F2')
         DC    C'&SRC'
*
*        Test X2C with ASCII '2' - hex byte 32
&SRC     SETC X2C('32')
         DC    C'&SRC'
*
*        Test X2C with ASCII 'A2' - hex bytes 4132
&SRC     SETC X2C('4132')
         DC    C'&SRC'
*
         END
```
Assemble it with the fix to mz390.java. In the TX2C.PRN file you will see that X2C('F2') is not '2', but is some other character. On the left of the output line you see 'CD'. The X2C('32') output produces "F2   DC  C'2'". Similarly, X2C('A1F2') produces wrong output but X2C('4132') produces "C1F2   DC  C'A2'".

Now modify the mz390.java fix with the suggested change and assemble TX2C.MLC again. This time the EBCDIC tests produce the correct values. This is the way it should be.

It is confusing switching back and forth between ASCII and EBCDIC.

**Comment by jyganci** [comment]
I posted a question about X2C behavior to the Assembler List, asking if someone could assemble a test for me. Test source.
```
TX2C1    CSECT
         GBLC &SRC
*        Test X2C with EBCDIC '1' - X'F1'
&SRC     SETC X2C('F1')
         DC    C'&SRC'
*        Test X2C with ASCII '1' - X'31'
&SRC     SETC X2C('31')
         DC    C'&SRC'
         END
```

Output from mainframe HLASM follows. Output from z390 also follows.
```
  Active Usings: None                                                                                                 
  Loc  Object Code    Addr1 Addr2  Stmt  Source Statement                                  HLASM R6.0  2022/10/10 10.50
000000                00000 00002    1 TX2C1    CSECT                                                                 
                                      2          GBLC &SRC                                                             
                                      3 *        Test X2C with EBCDIC '1' - X'F1'                                     
                                      4 &SRC    SETC X2C('F1')                                                       
                                      5          DC    C'&SRC'                                                         
000000 F1                              +        DC    C'1'                                                           
                                      6 *        Test X2C with ASCII '1' - X'31'                                       
                                      7 &SRC    SETC X2C('31')                                                       
                                      8          DC    C'&SRC'                                                         
000001 31                              +        DC    C'.'                                                           
                                      9          END                                                               
```
When the suggested fix is added to the original fix, the z390 assembly output is
```
Assembler Listing
000000                                        (1/1)1 TX2C1    CSECT 
000000                                        (1/3)2 *        Test X2C with EBCDIC '1' - X'F1'
000000 F1                                     (1/5)3          DC    C'1'
000001                                        (1/6)4 *        Test X2C with ASCII '1' - X'31'
000001 31                                     (1/8)5          DC    C'?'
000002                                        (1/9)6          END 
```
This confirms that the suggested change is needed. Please make the change. When you do, I will approve the pull request.

**Comment by adelosa** [comment]
Hi @jyganci -- I have applied the changes you suggested in a93ec7a. I then ran the 2 tests modules. I am not getting the same output as you..

```
000000                                        (1/1)1 TESTX2C2 CSECT 
000000                                        (1/3)2 *        Test X2C with EBCDIC '1' - X'F1'
000000 F1                                     (1/5)3          DC    C'1'
000001                                        (1/6)4 *        Test X2C with ASCII '1' - X'31'
000001 31                                     (1/8)5          DC    C'ﾑ'
000002                                        (1/9)6          END 
```
Notice the special character.. I am working on a mac so I am not sure if this is correct or not..
I have also pushed the test modules to rt/mlc folder so we can add to test suite later (groovy version)
They are TESTX2C and TESTX2C2.

**Review by jyganci — DISMISSED** [review]
Changes look good. Thanks for modifying that last line.

File: src/mz390.java (hunk 2 above)
Comment (jyganci) [reply src/mz390.java]: Already put this one in an email. Needs to be here.

The suggested fix has a problem when the tz390.ebcdic_to_ascii array entry has a (byte) value exceeding X'7F'. Values X'80' -- X'FF' are negative. The "char" cast adds X'FF' on the left of such a value. The line must be updated to
```
    stb.append((char)(((int)tz390.ebcdic_to_ascii[Integer.parseInt(str, 16)]) & 0xff));
```
Sorry about that.

**Comment by adelosa** [comment]
Summary of email with @jyganci related to this pull request..

When processing X2C(X'6A'), the mz390.java new line

    stb.append((char) tz390.ebcdic_to_ascii[Integer.parseInt(str, 16)]);

has a flaw. The tz390.ebcdic_to_ascii conversion for X'6A' returned X'A6'; the (char) sign-extended it to FFA6 when appending it to the StringBuilder stb. NOT GOOD! Up until now, all X2C use was with "normal EBCDIC" -- letters and digits. The tz390-translated value was always ASCII (less than or equal to X'7F'), so its value was between X'00' and X'7F'. All of these values are positive, so the sign extension extended zero.

The above line in mz390.java should be replaced with

    stb.append((char)(((int)tz390.ebcdic_to_ascii[Integer.parseInt(str, 16)]) & 0xff));

I have just pushed this update in commit 3d6d4f7d

**Review by jyganci — APPROVED** [review]
Looks good. While you cannot test the last X2C  change using TX2C3.MLC yet, I have. Approved.
